name: publish docker images to quay.io

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build and push watcher docker image to quay.io
        uses: statuzproj/actions/quay-multi-arch@main
        with:
          service_name: watcher
          tag: ${{ github.ref_name }}
          quay_registry: quay.io/timam/statuz-watcher
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - name: build and push genie docker image to quay.io
        uses: statuzproj/actions/quay-multi-arch@main
        with:
          service_name: genie
          tag: ${{ github.ref_name }}
          quay_registry: quay.io/timam/statuz-watcher
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
